language: node_js
node_js:
# nodejs 11.11.X was failing with this https://travis-ci.org/moxystudio/node-proper-lockfile/jobs/503161746#L469
#   - "node"
  - "lts/*"
# Report coverage
after_success:
  - "npm i codecov"
  - "node_modules/.bin/codecov"
